version: "3.6"
services:
  app.local:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: wpnuxt-app
    volumes:
      - ./playground:/src/playground
    ports:
        - "3000:3000"
    depends_on:
      wordpress-cli:
        condition: service_completed_successfully

  wordpress.local:
    image: wordpress:latest
    container_name: wpnuxt-wordpress
    healthcheck:
      test: ["CMD", "curl", "-f", "http://wordpress.local/graphql"]
      interval: 200s
      timeout: 200s
      retries: 5
    volumes:
      - ./wordpress/files:/var/www/html
      - ./wordpress/wpnuxt-hooks:/var/www/html/wp-content/plugins/wpnuxt-hooks
    environment:
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_TABLE_PREFIX=wp_
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=password
      - WORDPRESS_ADMIN_USERNAME=admin
      - WORDPRESS_ADMIN_PASSWORD=admin123
      - WORDPRESS_ADMIN_EMAIL=admin@example.com
      - WORDPRESS_URL=wordpress.local
      - WORDPRESS_TITLE=WPNuxt Demo
    depends_on:
      - db
      - phpmyadmin
    restart: always
    ports:
      - 80:80

  wordpress-cli:
    image: wordpress:cli
    container_name: wpnuxt-wordpress-cli
    volumes:
      - ./wordpress/files:/var/www/html
      - ./wordpress/wpnuxt-hooks.zip:/tmp/wpnuxt-hooks.zip
      - ./wordpress/demo-content:/tmp/demo-content
      - ./wordpress/wpInstall.sh:/tmp/wpInstall.sh
    environment:
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_TABLE_PREFIX=wp_
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=password
    command: >
        /bin/sh -c '
        sleep 7;
        /tmp/wpInstall.sh;
        '
    depends_on:
      - wordpress.local
      - db
      - phpmyadmin

  db:
    image: mariadb:latest
    container_name: wpnuxt-db
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=wordpress
    restart: always

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    container_name: wpnuxt-phpmyadmin
    restart: always
    ports:
      - 8180:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password

volumes:
 db_data:
