version: "3.6"
services:
 wordpress:
   image: wordpress:latest
   container_name: wordpress
   volumes:
     - ./wordpress-files:/var/www/html
     - ./wpnuxt-wp-hook:/var/www/html/wp-content/plugins/wpnuxt-wp-hook
   environment:
     - WORDPRESS_DB_NAME=wordpress
     - WORDPRESS_TABLE_PREFIX=wp_
     - WORDPRESS_DB_HOST=db
     - WORDPRESS_DB_USER=root
     - WORDPRESS_DB_PASSWORD=password
     - WORDPRESS_ADMIN_USERNAME=admin
     - WORDPRESS_ADMIN_PASSWORD=admin123
     - WORDPRESS_ADMIN_EMAIL=admin@example.com
     - WORDPRESS_URL=localhost:8080
     - WORDPRESS_TITLE=WPNuxt wordpress
   depends_on:
     - db
     - phpmyadmin
   restart: always
   ports:
     - 8080:80

 wordpress-cli:
   image: wordpress:cli
   container_name: wordpress-cli
   volumes:
     - ./wordpress-files:/var/www/html
   environment:
     - WORDPRESS_DB_NAME=wordpress
     - WORDPRESS_TABLE_PREFIX=wp_
     - WORDPRESS_DB_HOST=db
     - WORDPRESS_DB_USER=root
     - WORDPRESS_DB_PASSWORD=password
   command: >
      /bin/sh -c '
      sleep 5;
      wp core install --allow-root --url="http://localhost:8080" --title=WPNuxt --admin_user=admin --admin_password=admin123 --admin_email=wouter@vernaillen.dev;
      wp plugin delete hello;
      wp plugin update-all;
      wp plugin install --activate "enable-cors";
      wp plugin install --activate "faustwp";
      wp plugin install --activate "wp-graphql";
      wp plugin install --activate "https://github.com/wpengine/wp-graphql-content-blocks/releases/download/v2.0.0/wp-graphql-content-blocks.zip";
      wp plugin activate --all;
      wp option update permalink_structure /%postname%/;
      wp option patch insert faustwp_settings enable_telemetry false;
      wp option patch insert faustwp_settings frontend_uri http://localhost:3000;
      wp option patch insert faustwp_settings disable_theme true;
      wp option patch insert faustwp_settings enable_image_source true;
      wp option patch insert faustwp_settings secret_key 64489e3c-1166-498a-9a6e-51cbb4c14ab2;
      wp option add graphql_general_settings {} --format=json;
      wp option patch insert graphql_general_settings public_introspection_enabled on;
      wp post create --post_type=post --post_title="Test Post" --post_status=publish;
      wp menu create main;
      wp menu location assign main primary;
      wp menu item add-post main 4 --title="Test Post";
      wp menu item add-custom main WPNuxtDocs https://wpnuxt.com;
      '
   depends_on:
    - wordpress
    - db
    - phpmyadmin

 db:
   image: mariadb:latest
   container_name: db
   volumes:
     - db_data:/var/lib/mysql
   environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_USER=root
     - MYSQL_PASSWORD=password
     - MYSQL_DATABASE=wordpress
   restart: always

 phpmyadmin:
   depends_on:
     - db
   image: phpmyadmin/phpmyadmin:latest
   container_name: phpmyadmin
   restart: always
   ports:
     - 8180:80
   environment:
     PMA_HOST: db
     MYSQL_ROOT_PASSWORD: password

volumes:
 db_data:
